<?php

return [
    'luxury_noir' => [
        'name' => 'Luxury Noir',
        'description' => 'Sophisticated, premium dark theme with gold accents',
        'glass_opacity' => 0.08,
        'glass_blur' => 40,
        'shadow_style' => 'deep',
        'shadow_intensity' => 1.0,
        'border_radius' => 16,
        'border_radius_unit' => 'px',
        'card_style' => 'floating',
        'motion_preset' => 'cinematic',
        'animation_speed' => 1.0,
        'spring_stiffness' => 300,
        'spring_damping' => 25,
        'icon_style' => 'luxury',
        'icon_weight' => 'regular',
        'background_type' => 'salon_image',
        'cursor_style' => 'luxury',
        'sidebar_style' => 'glass',
        'button_style' => 'glass',
        'default_colors' => [
            'primary' => '#FF622B',
            'secondary' => '#FF8C5A',
            'accent' => '#FFD700',
            'background' => '#0A0A0A',
            'surface' => '#1A1A1A',
        ],
    ],

    'modern_glass' => [
        'name' => 'Modern Glass',
        'description' => 'Clean, contemporary with cool blue tones',
        'glass_opacity' => 0.12,
        'glass_blur' => 40,
        'shadow_style' => 'soft',
        'shadow_intensity' => 0.8,
        'border_radius' => 20,
        'border_radius_unit' => 'px',
        'card_style' => 'floating',
        'motion_preset' => 'elegant',
        'animation_speed' => 0.9,
        'spring_stiffness' => 250,
        'spring_damping' => 20,
        'icon_style' => 'minimal',
        'icon_weight' => 'thin',
        'background_type' => 'abstract',
        'cursor_style' => 'default',
        'sidebar_style' => 'glass',
        'button_style' => 'glass',
        'default_colors' => [
            'primary' => '#3B82F6',
            'secondary' => '#60A5FA',
            'accent' => '#8B5CF6',
            'background' => '#F5F5F5',
            'surface' => '#FFFFFF',
        ],
    ],

    'urban_pulse' => [
        'name' => 'Urban Pulse',
        'description' => 'Edgy, energetic with bold colors and dynamic motion',
        'glass_opacity' => 0.10,
        'glass_blur' => 30,
        'shadow_style' => 'colored',
        'shadow_intensity' => 1.2,
        'border_radius' => 12,
        'border_radius_unit' => 'px',
        'card_style' => 'elevated',
        'motion_preset' => 'quick',
        'animation_speed' => 1.2,
        'spring_stiffness' => 400,
        'spring_damping' => 20,
        'icon_style' => 'filled',
        'icon_weight' => 'bold',
        'background_type' => 'particles',
        'cursor_style' => 'magnetic',
        'sidebar_style' => 'solid',
        'button_style' => 'solid',
        'default_colors' => [
            'primary' => '#FF6B35',
            'secondary' => '#FF8E53',
            'accent' => '#00FF88',
            'background' => '#1A1A2E',
            'surface' => '#16213E',
        ],
    ],

    'minimal_zen' => [
        'name' => 'Minimal Zen',
        'description' => 'Calm, peaceful with natural tones and soft motion',
        'glass_opacity' => 0.06,
        'glass_blur' => 50,
        'shadow_style' => 'soft',
        'shadow_intensity' => 0.6,
        'border_radius' => 24,
        'border_radius_unit' => 'px',
        'card_style' => 'flat',
        'motion_preset' => 'organic',
        'animation_speed' => 0.8,
        'spring_stiffness' => 150,
        'spring_damping' => 30,
        'icon_style' => 'minimal',
        'icon_weight' => 'thin',
        'background_type' => 'gradient',
        'cursor_style' => 'default',
        'sidebar_style' => 'glass',
        'button_style' => 'outline',
        'default_colors' => [
            'primary' => '#2F7A5C',
            'secondary' => '#8FB996',
            'accent' => '#C9D4A5',
            'background' => '#F5F8F5',
            'surface' => '#FFFFFF',
        ],
    ],

    'organic' => [
        'name' => 'Organic',
        'description' => 'Natural, earthy with rounded edges and nature textures',
        'glass_opacity' => 0.08,
        'glass_blur' => 35,
        'shadow_style' => 'soft',
        'shadow_intensity' => 0.7,
        'border_radius' => 32,
        'border_radius_unit' => 'px',
        'card_style' => 'floating',
        'motion_preset' => 'organic',
        'animation_speed' => 0.9,
        'spring_stiffness' => 200,
        'spring_damping' => 28,
        'icon_style' => 'outlined',
        'icon_weight' => 'regular',
        'background_type' => 'salon_image',
        'cursor_style' => 'default',
        'sidebar_style' => 'glass',
        'button_style' => 'ghost',
        'default_colors' => [
            'primary' => '#5B8A5B',
            'secondary' => '#8FB996',
            'accent' => '#D4A574',
            'background' => '#F0F5F0',
            'surface' => '#FFFFFF',
        ],
    ],

    'classic_barber' => [
        'name' => 'Classic Barber',
        'description' => 'Traditional, masculine with navy and copper tones',
        'glass_opacity' => 0.10,
        'glass_blur' => 40,
        'shadow_style' => 'deep',
        'shadow_intensity' => 1.0,
        'border_radius' => 8,
        'border_radius_unit' => 'px',
        'card_style' => 'elevated',
        'motion_preset' => 'elegant',
        'animation_speed' => 1.0,
        'spring_stiffness' => 300,
        'spring_damping' => 25,
        'icon_style' => 'filled',
        'icon_weight' => 'regular',
        'background_type' => 'salon_image',
        'cursor_style' => 'default',
        'sidebar_style' => 'solid',
        'button_style' => 'solid',
        'default_colors' => [
            'primary' => '#1A365D',
            'secondary' => '#2C5282',
            'accent' => '#B87333',
            'background' => '#F5F0E8',
            'surface' => '#FFFFFF',
        ],
    ],

    'neon_future' => [
        'name' => 'Neon Future',
        'description' => 'Futuristic, cyberpunk with neon colors and glow effects',
        'glass_opacity' => 0.15,
        'glass_blur' => 25,
        'shadow_style' => 'colored',
        'shadow_intensity' => 1.5,
        'border_radius' => 4,
        'border_radius_unit' => 'px',
        'card_style' => 'floating',
        'motion_preset' => 'quick',
        'animation_speed' => 1.3,
        'spring_stiffness' => 500,
        'spring_damping' => 15,
        'icon_style' => 'filled',
        'icon_weight' => 'bold',
        'background_type' => 'particles',
        'cursor_style' => 'magnetic',
        'sidebar_style' => 'glass',
        'button_style' => 'solid',
        'default_colors' => [
            'primary' => '#FF00FF',
            'secondary' => '#00FFFF',
            'accent' => '#FFFF00',
            'background' => '#0D0D0D',
            'surface' => '#1A1A2E',
        ],
    ],

    'executive' => [
        'name' => 'Executive',
        'description' => 'Professional, corporate with navy and silver tones',
        'glass_opacity' => 0.08,
        'glass_blur' => 45,
        'shadow_style' => 'deep',
        'shadow_intensity' => 0.9,
        'border_radius' => 12,
        'border_radius_unit' => 'px',
        'card_style' => 'elevated',
        'motion_preset' => 'elegant',
        'animation_speed' => 0.9,
        'spring_stiffness' => 280,
        'spring_damping' => 22,
        'icon_style' => 'minimal',
        'icon_weight' => 'regular',
        'background_type' => 'gradient',
        'cursor_style' => 'default',
        'sidebar_style' => 'solid',
        'button_style' => 'outline',
        'default_colors' => [
            'primary' => '#1E3A8A',
            'secondary' => '#3B82F6',
            'accent' => '#C0C0C0',
            'background' => '#F8FAFC',
            'surface' => '#FFFFFF',
        ],
    ],
];
