[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/yo.salon/backend/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/yo.salon/backend/storage/logs/worker.log
stopwaitsecs=3600

[program:laravel-scheduler]
process_name=%(program_name)s
command=php /var/www/yo.salon/backend/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/yo.salon/backend/storage/logs/scheduler.log

[program:laravel-reverb]
process_name=%(program_name)s
command=php /var/www/yo.salon/backend/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/yo.salon/backend/storage/logs/reverb.log
